name: hello

on:
  workflow_dispatch:

jobs:
  hello:
    # codebuild-<CodeBuild プロジェクト名>-<run_id>-<run_attempt>
    runs-on: codebuild-gha-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Hello
        run: echo "Hello, world!"

      - name: Where am I
        run: |
          uname -a
          echo "CODEBUILD_BUILD_ID=${CODEBUILD_BUILD_ID}"
          aws sts get-caller-identity
